### ISSUE TITLE
Fails on Emacs 23

### ISSUE THREAD

**Issue by jandrieu** [joshwnj/json-mode#30]
I have marmalade and package.el installed, but when I try to run 
```
M-x package-install json-mode
```
Emacs complains with 
```
Package `emacs-24' is unavailable.
```
I get the same result using package-install-file with the json-mode.el file downloaded into ~/.emacs.d/

FWIW, I'm running GNU Emacs 23.3.1.

Any suggestions?

**Comment by joshwnj** [comment]
Huh, sorry about that - it's been awhile since I've tried this on emacs 23 :)  I can see that the `json-snatcher` dependency requires emacs 24, so that might be the issue.

Could you please try manually replacing your `json-mode.el` with the one in this branch and let me know if that's any different? https://github.com/joshwnj/json-mode/blob/23-compatible/json-mode.el

Thanks

**Comment by joshwnj** [comment]
Also marmalade seems pretty abandoned (I haven't been able to login to update my packages for months) so I'd recommend using http://melpa.org/#/json-mode for now

**Comment by prvteprts** [comment]
I tried json-mode with Emacs 23.3.1 by manually copying json-mode.el (plus the required files for json-snatcher and json-reformat) and editing my config file. Everything went smoothly enough, except for the use of `split-window-below`, which I changed accordingly to `split-window-vertically`.

@joshwnj Are you amenable to back-porting this project to version 23? Seems like a straightforward fix which I believe I can help out with.

**Comment by joshwnj** [comment]
@prvteprts absolutely. Could you please put your modified version on github somewhere I can take a look at what needs to change? Thanks!

**Comment by prvteprts** [comment]
@joshwnj Sorry for following up on this after almost a year! I made a PR: https://github.com/joshwnj/json-mode/pull/41

**Comment by joshwnj** [comment]
@prvteprts thanks!
